import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useState } from 'react'
import { useSession } from 'next-auth/react'

export default function Home() {

  const { data:session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session ? User({session}) : Guest()}
    </div>
  )
}

function Guest(){
  return(
    <main className="container mx-auto text-center py-20">
        <h3 className="text-4xl font-bold">Guest Homepage</h3>
        <div className="flex justify-center">
          <Link href={'/login'}>Sign In</Link>
        </div>
      </main>
  )
}

const User = ({session}) => {
  return(
    <main className="container mx-auto text-center py-20">
        <h3 className="text-4xl font-bold">Authorized User Homepage</h3>

        <div className="details">
          <h5>{session.user.name}</h5>
          <h5>{session.user.email}</h5>
        </div>
        
        <div>
          <button className="mt-5 px-10 py-1 rounded-sm bg-indigo-500 bg-gray-50">Sign Out</button>
        </div>

        <div className="flex justify-center">
          <Link href={'/profile'}>Profile</Link>
        </div>
      </main>
  )
}